### ISSUE TITLE
[Bug]: default cn/dn cache volume error

### ISSUE THREAD

**Issue by wanglei4687** [matrixorigin/matrixone-operator#207]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When we not set cache volume, it will have volumeMount but not have volume created.

### Expected Behavior

using memory storage

**Comment by aylei** [comment]
closed by #218
