### ISSUE TITLE
[Bug]: after delete mo，apply cn groups config, show backend servers labels is null

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone-operator#345]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-c74710ac
- Hardware parameters:
- OS type:
- Others:

### Actual Behavior

<img width="1434" alt="企业微信截图_9acff523-a477-4432-a730-7718139672c1" src="https://user-images.githubusercontent.com/113406637/236608594-c81c5541-154c-4983-9427-1dab6a6b9b47.png">

### Steps to Reproduce

1.delete -f mo.yaml
2.apply -f mo.yaml, config cn groups
3.show backend servers;

**Comment by aylei** [comment]
@heni02 fixed via #346 , please kindly close if the issue is addressed

**Comment by heni02** [comment]
comfirm，closed
![image](https://github.com/matrixorigin/matrixone-operator/assets/113406637/9ab07c22-c87a-469a-b18c-49002e9276ec)
