### ISSUE TITLE
[Docs]: will seccomp profile of CRI runtime block MO's syscall

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone-operator#402]
### Is there an existing issue about documentation?

- [X] I have checked the existing issues.

### Describe the issue

follow up https://github.com/matrixorigin/matrixone/issues/10593#issuecomment-1678778723

we need to figure out whether the scecomp profile of CRD runtime will block MO's syscall in k8s env.

**Comment by loveRhythm1990** [comment]
There are three options setting seccomp in K8s cluster, and the default options is `Unconfined`, so the issue in #10598 will not affect MO in K8s cluster.

- Unconfined: disable seccomp mode
- RuntimeDefault: use runtime default seccomp file, like [docker default profile](https://github.com/moby/moby/blob/master/profiles/seccomp/default.json)
- Localhost: use a self-defined profile in K8s node

this can be verified by check seccomp mode inside docker by command `cat /proc/1/status | grep Seccomp`, according to [proc manpage](https://man7.org/linux/man-pages/man5/proc.5.html) , `0` means `SECCOMP_MODE_DISABLED `, in our cluster this option is `0`, like:
<img width="916" alt="企业微信截图_47af8e96-038a-4aa5-be89-ee4b7c849b24" src="https://github.com/matrixorigin/matrixone-operator/assets/52204121/37c757fa-9d2e-4ac4-bdef-eec96710d99f">
and if we start a container by docker command, it is `2` which is `SECCOMP_MODE_FILTER ` mode.
<img width="529" alt="企业微信截图_97928114-28eb-4190-b52a-33af22d9a5c9" src="https://github.com/matrixorigin/matrixone-operator/assets/52204121/d6ba65b4-8fcf-4638-a838-ca0967c4237e">

**Comment by aylei** [comment]
@loveRhythm1990 good summary! Closing as we don't need to worry about seccomp profile by default.
