### ISSUE TITLE
[Enhancement]: rename dn to tn

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone-operator#414]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

MatrixOne 1.0 has renamed its DN(data node) to TN(transaction node), the operator yaml needs to be updated as well.

**Comment by aylei** [comment]
The yaml can be modified to accept TN and DN(as an alias of TN), but DN will still remains in k8s CRD and pod name
