### ISSUE TITLE
[Feature Request]: helm chart 提供全局镜像仓库变量设置

### ISSUE THREAD

**Issue by jinqinghui** [matrixorigin/matrixone-operator#446]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

operator helm chart 会用在私有化部署场景，这里将使用私有化的镜像库。operator依赖operator和kruise镜像地址，现在当切换到私有化仓库时，需要修改两次镜像地址。如果未来依赖更多镜像，每次切私有化镜像仓库，都需要写多次私仓地址。

### Describe the feature you'd like

希望有个全局镜像仓库变量，设置完后，operator依赖的所有镜像都从这个私仓拿。这样方便私有化部署切换到私有仓库。

**Comment by aylei** [comment]
增加：对 mobr 镜像的管理
