### ISSUE TITLE
Document Improvement

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone-operator#97]
1. Add limitations in the readme, such as, but not limited to 
    -    The Operator currently runs on TKE/EKS. GKE, AKC, and other Managed Public Cloud k8s have not been tested.
    -    multi-region is not supported yet.
    -    The Operator only supported max to 3 nodes cluster
    -    The Operator does not yet include monitor, istio, etc.

2. Refine deploy docs.

**Comment by wanglei4687** [comment]
@sukki37 got it
